#!/bin/sh

sudo xbps-install -S font-awesome
sudo xbps-install -S nerd-fonts
sudo xbps-install -S neovim
sudo xbps-install -S tmux
sudo xbps-install -S kitty
sudo xbps-install -S zsh
sudo xbps-install -S zsh-completions
sudo xbps-install -S zsh-autosuggestion
sudo xbps-install -S zsh-syntax-highlighting
sudo xbps-install -S redshift
sudo xbps-install -S curl

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
chmod +x install.sh
./install.sh
rm $HOME/.zshrc
rm $HOME/.bash_history
rm $HOME/.bash_logout
rm $HOME/.bash_profile
rm $HOME/.bashrc

config="$HOME/.config"
dotfiles="$HOME/dotfiles"

mkdir $HOME/.config

ln -s "$dotfiles/nvim" "$config/nvim"
ln -s "$dotfiles/tmux" "$config/tmux"
ln -s "$dotfiles/picom" "$config/picom"
ln -s "$dotfiles/kitty" "$config/kitty"
ln -s "$dotfiles/redshift" "$config/redshift"
ln -s "$dotfiles/zshrc" "$HOME/.zshrc"
ln -s "$dotfiles/xinitrc" "$HOME/.xinitrc"

cd dwm
sudo make install

cd ../dwmblocks
sudo make install

