#!/bin/bash

apps=(
	# 'mopidy'
	'dwmblocks'
	'$HOME/.local/bin/picom/build/src/picom'
  # 'pulseaudio'
  'pipewire'
  'pipewire-pulse'
	#'dropbox'
)

for app in ${apps[@]}; do
	pgrep="$(pgrep $app)"
	if [[ $pgrep == "" ]]; then
		eval $app &
	fi
done

#xautolock -time 15 -locker "slock && systemctl suspend" -detectsleep
pkill redshift
redshift &
feh --no-fehbg --bg-scale -z $HOME/dotfiles/wallpapers
setxkbmap -option caps:escape
#wal -Rq
# exec dbus-launch --exit-with-session dwm
while type dwm >/dev/null ; do dbus-launch --exit-with-session dwm && continue || break ; done
