export PATH=$HOME/bin:/usr/local/bin:$HOME/.local/share/flatpak/exports/bin:$PATH
EDITOR="nvim"
export ZSH="/home/aidan/dotfiles/zsh/oh-my-zsh"
ZSH_THEME="robbyrussell"
# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="false"

plugins=(
    git
    zsh-autosuggestions
	colored-man-pages
)

source $ZSH/oh-my-zsh.sh

# for jdtls
export PATH=$PATH:$HOME/.local/bin

setbg () {
	dir=$(pwd)
	WALLPAPER=$( find "$HOME/dotfiles/wallpapers" -type f -print0 | shuf -z -n 1 )
  feh --no-fehbg --bg-fill $WALLPAPER
}

# aliases
alias w=setbg
alias v="nvim"
alias k="kak"
alias n="ncmpcpp -q"
alias fet="neofetch"
alias fzf="fzf --color bg:-1"

lo () {
	libreoffice $1 &>/dev/null &
}

fcd () {
  cd "$(find $HOME -type d | fzf --preview 'tree {}')"
}

images () {
  xclip "$(find . -type f | fzf --preview 'chafa {}')"
}

op () {
    fcd
    nvim
}

open () {
  devour xdg-open "$(find -type f | fzf)"
}

run () {
	dir=$(pwd)
	$dir/run
}

leaguefix () {
	sudo sysctl -w abi.vsyscall32=0
}

slocksuspend () {
	systemctl suspend
	slock
}
# export XDG_RUNTIME_DIR=/run/user/$(id -u aidan)
alias spending=slocksuspend
alias sus=slocksuspend
source /home/aidan/dotfiles/zsh/oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
export PATH=$HOME/.local/bin/statusbar:$PATH
cd
alias luamake=/home/aidan/lua-language-server/3rd/luamake/luamake
